#ifndef LETTERMODELS_GLOBAL_H
#define LETTERMODELS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LETTERMODELS_LIBRARY)
#  define LETTERMODELSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LETTERMODELSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // LETTERMODELS_GLOBAL_H
